// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mylog2_HH_
#define _mylog2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "mylog2_fadd_32ns_bkb.h"
#include "mylog2_fmul_32ns_cud.h"
#include "mylog2_uitofp_32ndEe.h"
#include "mylog2_sitofp_32neOg.h"
#include "mylog2_mul_41ns_4fYi.h"
#include "mylog2_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 5,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct mylog2 : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    mylog2(sc_module_name name);
    SC_HAS_PROCESS(mylog2);

    ~mylog2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mylog2_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* mylog2_AXILiteS_s_axi_U;
    mylog2_fadd_32ns_bkb<1,5,32,32,32>* mylog2_fadd_32ns_bkb_U1;
    mylog2_fmul_32ns_cud<1,4,32,32,32>* mylog2_fmul_32ns_cud_U2;
    mylog2_uitofp_32ndEe<1,6,32,32>* mylog2_uitofp_32ndEe_U3;
    mylog2_sitofp_32neOg<1,6,32,32>* mylog2_sitofp_32neOg_U4;
    mylog2_mul_41ns_4fYi<1,2,41,41,64>* mylog2_mul_41ns_4fYi_U5;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<25> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > x;
    sc_signal< sc_logic > y_ap_vld;
    sc_signal< sc_lv<32> > res_lo_0_reg_168;
    sc_signal< sc_lv<41> > val_2_reg_180;
    sc_signal< sc_lv<5> > i_0_reg_189;
    sc_signal< sc_lv<23> > tmp_V_1_fu_233_p1;
    sc_signal< sc_lv<23> > tmp_V_1_reg_502;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<9> > add_ln339_fu_241_p2;
    sc_signal< sc_lv<9> > add_ln339_reg_507;
    sc_signal< sc_lv<1> > isNeg_reg_512;
    sc_signal< sc_lv<8> > sub_ln1311_fu_255_p2;
    sc_signal< sc_lv<8> > sub_ln1311_reg_518;
    sc_signal< sc_lv<32> > val_V_fu_329_p3;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > zext_ln21_fu_364_p1;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > icmp_ln18_fu_346_p2;
    sc_signal< sc_lv<32> > res_hi_fu_368_p2;
    sc_signal< sc_lv<1> > icmp_ln24_fu_384_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > val_4_fu_400_p1;
    sc_signal< sc_lv<32> > res_hi_2_fu_404_p2;
    sc_signal< sc_lv<41> > zext_ln31_1_fu_410_p1;
    sc_signal< sc_lv<1> > icmp_ln31_fu_414_p2;
    sc_signal< sc_lv<1> > icmp_ln31_reg_560;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<5> > i_fu_420_p2;
    sc_signal< sc_lv<5> > i_reg_564;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<64> > zext_ln31_fu_426_p1;
    sc_signal< sc_lv<1> > icmp_ln36_fu_446_p2;
    sc_signal< sc_lv<1> > icmp_ln36_reg_575;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< bool > ap_block_state9_pp0_stage1_iter0;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_lv<31> > trunc_ln36_fu_452_p1;
    sc_signal< sc_lv<31> > trunc_ln36_reg_581;
    sc_signal< sc_lv<41> > tmp_s_reg_586;
    sc_signal< sc_lv<40> > tmp_14_reg_591;
    sc_signal< sc_lv<32> > res_lo_fu_481_p3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<41> > select_ln36_fu_491_p3;
    sc_signal< sc_lv<32> > grp_fu_211_p1;
    sc_signal< sc_lv<32> > tmp_4_reg_606;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<32> > grp_fu_204_p2;
    sc_signal< sc_lv<32> > tmp_6_reg_611;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_lv<32> > grp_fu_215_p1;
    sc_signal< sc_lv<32> > tmp_7_reg_616;
    sc_signal< sc_lv<32> > grp_fu_200_p2;
    sc_signal< sc_lv<32> > tmp_8_reg_621;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state8;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< sc_lv<32> > res_hi_0_reg_125;
    sc_signal< sc_lv<32> > val_0_reg_137;
    sc_signal< sc_lv<32> > res_hi_1_reg_147;
    sc_signal< sc_lv<32> > val_1_reg_158;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<41> > ap_phi_mux_val_2_phi_fu_183_p4;
    sc_signal< sc_lv<5> > ap_phi_mux_i_0_phi_fu_193_p4;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<32> > grp_fu_204_p0;
    sc_signal< sc_lv<32> > grp_fu_204_p1;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<32> > p_Val2_s_fu_219_p1;
    sc_signal< sc_lv<8> > tmp_V_fu_223_p4;
    sc_signal< sc_lv<9> > zext_ln339_fu_237_p1;
    sc_signal< sc_lv<25> > mantissa_V_fu_261_p4;
    sc_signal< sc_lv<9> > sext_ln1311_fu_274_p1;
    sc_signal< sc_lv<9> > ush_fu_277_p3;
    sc_signal< sc_lv<32> > sext_ln1311_1_fu_283_p1;
    sc_signal< sc_lv<25> > sext_ln1311_2_fu_287_p1;
    sc_signal< sc_lv<79> > zext_ln682_fu_270_p1;
    sc_signal< sc_lv<79> > zext_ln1287_fu_291_p1;
    sc_signal< sc_lv<25> > r_V_fu_295_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_307_p3;
    sc_signal< sc_lv<79> > r_V_1_fu_301_p2;
    sc_signal< sc_lv<32> > zext_ln662_fu_315_p1;
    sc_signal< sc_lv<32> > tmp_9_fu_319_p4;
    sc_signal< sc_lv<9> > tmp_10_fu_336_p4;
    sc_signal< sc_lv<23> > trunc_ln21_fu_352_p1;
    sc_signal< sc_lv<24> > val_fu_356_p3;
    sc_signal< sc_lv<8> > tmp_12_fu_374_p4;
    sc_signal< sc_lv<31> > val_3_fu_390_p4;
    sc_signal< sc_lv<41> > grp_fu_430_p0;
    sc_signal< sc_lv<41> > grp_fu_430_p1;
    sc_signal< sc_lv<64> > grp_fu_430_p2;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<17> > tmp_13_fu_436_p4;
    sc_signal< sc_lv<1> > xor_ln36_fu_476_p2;
    sc_signal< sc_lv<41> > zext_ln36_fu_488_p1;
    sc_signal< sc_lv<25> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<25> ap_ST_fsm_state1;
    static const sc_lv<25> ap_ST_fsm_state2;
    static const sc_lv<25> ap_ST_fsm_state3;
    static const sc_lv<25> ap_ST_fsm_state4;
    static const sc_lv<25> ap_ST_fsm_state5;
    static const sc_lv<25> ap_ST_fsm_state6;
    static const sc_lv<25> ap_ST_fsm_state7;
    static const sc_lv<25> ap_ST_fsm_pp0_stage0;
    static const sc_lv<25> ap_ST_fsm_pp0_stage1;
    static const sc_lv<25> ap_ST_fsm_state11;
    static const sc_lv<25> ap_ST_fsm_state12;
    static const sc_lv<25> ap_ST_fsm_state13;
    static const sc_lv<25> ap_ST_fsm_state14;
    static const sc_lv<25> ap_ST_fsm_state15;
    static const sc_lv<25> ap_ST_fsm_state16;
    static const sc_lv<25> ap_ST_fsm_state17;
    static const sc_lv<25> ap_ST_fsm_state18;
    static const sc_lv<25> ap_ST_fsm_state19;
    static const sc_lv<25> ap_ST_fsm_state20;
    static const sc_lv<25> ap_ST_fsm_state21;
    static const sc_lv<25> ap_ST_fsm_state22;
    static const sc_lv<25> ap_ST_fsm_state23;
    static const sc_lv<25> ap_ST_fsm_state24;
    static const sc_lv<25> ap_ST_fsm_state25;
    static const sc_lv<25> ap_ST_fsm_state26;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_4B000000;
    static const sc_lv<32> ap_const_lv32_34000000;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<9> ap_const_lv9_181;
    static const sc_lv<8> ap_const_lv8_7F;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<5> ap_const_lv5_16;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<17> ap_const_lv17_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_add_ln339_fu_241_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_state10_pp0_stage0_iter1();
    void thread_ap_block_state8_pp0_stage0_iter0();
    void thread_ap_block_state9_pp0_stage1_iter0();
    void thread_ap_condition_pp0_exit_iter0_state8();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_i_0_phi_fu_193_p4();
    void thread_ap_phi_mux_val_2_phi_fu_183_p4();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_grp_fu_204_p0();
    void thread_grp_fu_204_p1();
    void thread_grp_fu_430_p0();
    void thread_grp_fu_430_p1();
    void thread_i_fu_420_p2();
    void thread_icmp_ln18_fu_346_p2();
    void thread_icmp_ln24_fu_384_p2();
    void thread_icmp_ln31_fu_414_p2();
    void thread_icmp_ln36_fu_446_p2();
    void thread_mantissa_V_fu_261_p4();
    void thread_p_Val2_s_fu_219_p1();
    void thread_r_V_1_fu_301_p2();
    void thread_r_V_fu_295_p2();
    void thread_res_hi_2_fu_404_p2();
    void thread_res_hi_fu_368_p2();
    void thread_res_lo_fu_481_p3();
    void thread_select_ln36_fu_491_p3();
    void thread_sext_ln1311_1_fu_283_p1();
    void thread_sext_ln1311_2_fu_287_p1();
    void thread_sext_ln1311_fu_274_p1();
    void thread_sub_ln1311_fu_255_p2();
    void thread_tmp_10_fu_336_p4();
    void thread_tmp_12_fu_374_p4();
    void thread_tmp_13_fu_436_p4();
    void thread_tmp_3_fu_307_p3();
    void thread_tmp_9_fu_319_p4();
    void thread_tmp_V_1_fu_233_p1();
    void thread_tmp_V_fu_223_p4();
    void thread_trunc_ln21_fu_352_p1();
    void thread_trunc_ln36_fu_452_p1();
    void thread_ush_fu_277_p3();
    void thread_val_3_fu_390_p4();
    void thread_val_4_fu_400_p1();
    void thread_val_V_fu_329_p3();
    void thread_val_fu_356_p3();
    void thread_xor_ln36_fu_476_p2();
    void thread_y_ap_vld();
    void thread_zext_ln1287_fu_291_p1();
    void thread_zext_ln21_fu_364_p1();
    void thread_zext_ln31_1_fu_410_p1();
    void thread_zext_ln31_fu_426_p1();
    void thread_zext_ln339_fu_237_p1();
    void thread_zext_ln36_fu_488_p1();
    void thread_zext_ln662_fu_315_p1();
    void thread_zext_ln682_fu_270_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
