[package]
name = "lab2"
version = "0.1.0"
authors = ["slimakanzer"]
edition = "2018"

[dependencies]
cgmath = "0.17.0"
gl = "0.14.0"
glfw = "0.40.0"
image = "0.19.0"
memoffset = "0.6.1"
rand = "0.7.3"
tobj = "2.0.0"